# **what?**
# Check if the an issue is opened near or during an extended holiday period.
# If so, post an automatically-generated comment about the holiday for bug reports.
# Also provide specific information to customers of dbt Cloud.

# **why?**
# Explain why responses will be delayed during our holiday period.

# **when?**
# This will run when new issues are opened.

name: Auto-Respond to Bug Reports During Holiday Period

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  auto-response:
    runs-on: ${{ vars.UBUNTU_LATEST }}
    steps:
      - name: Check if current date is within holiday period
        id: date-check
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          start_date="2024-12-23"
          end_date="2025-01-05"

          if [[ "$current_date" < "$start_date" || "$current_date" > "$end_date" ]]; then
            echo "outside_holiday=true" >> $GITHUB_ENV
          else
            echo "outside_holiday=false" >> $GITHUB_ENV
          fi

      - name: Post comment
        if: ${{ env.outside_holiday == 'false' && contains(github.event.issue.labels.*.name, 'bug') }}
        run: |
          gh issue comment ${{ github.event.issue.number }} --repo ${{ github.repository }} --body "Thank you for your bug report! Our team is will be out of the office for [Christmas and our Global Week of Rest](https://handbook.getdbt.com/docs/time_off#2024-us-holidays), from December 25, 2024, through January 3, 2025.

          We will review your issue as soon as possible after returning.
          Thank you for your understanding, and happy holidays! 🎄🎉

          If you are a customer of dbt Cloud, please contact our Customer Support team via the dbt Cloud web interface or email **support@dbtlabs.com**."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
